# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Bun Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        bun-version: [latest]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      # run any `bun` or `bunx` command
      - name: Install dependencies
        run: bun install
      
      - name: Run type check
        run: bun run check
      
      # PR builds - Only run read-only tests
      - name: Run tests (PR - readonly)
        if: github.event_name == 'pull_request'
        env:
          YOUTRACK_BASE_URL: ${{ secrets.YOUTRACK_BASE_URL }}
          YOUTRACK_TOKEN: ${{ secrets.YOUTRACK_TOKEN }}
          TEST_PROJECT_ID: ${{ secrets.TEST_PROJECT_ID }}
          ENABLE_UPDATES: 'false'
          RESTORE_STATE_AFTER_TEST: 'true'
        run: bun test
      
      # Master branch - Run all tests including those that modify data
      - name: Run tests (Master branch - full test suite)
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          YOUTRACK_BASE_URL: ${{ secrets.YOUTRACK_BASE_URL }}
          YOUTRACK_TOKEN: ${{ secrets.YOUTRACK_TOKEN }}
          TEST_PROJECT_ID: ${{ secrets.TEST_PROJECT_ID }}
          ENABLE_UPDATES: 'true'
          RESTORE_STATE_AFTER_TEST: 'true'
        run: bun test
