# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Bun.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      # ...
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      # run any `bun` or `bunx` command
      - name: Install dependencies
        run: bun install
      - name: Build package
        run: bun run build
      - name: Run tests
        run: bun test
